import { readEmail } from "../../../../src/emails.js"
import { createToken } from "../../../../src/tokens.js"; // Import createToken

export async function onRequestPost(context) {
  // Step 1: Parse JSON body for email
  let requestBody
  try {
    requestBody = await context.request.json()
  } catch (e) {
    return new Response(
      JSON.stringify({
        message: "Invalid request body. Please provide an email.", // Slightly more specific for bad requests
      }),
      { status: 400, headers: { "Content-Type": "application/json" } }
    )
  }

  const email = requestBody.email

  // Step 2: Input Validation
  if (!email || typeof email !== "string" || !email.includes("@")) {
    // Still return a generic message, but log the specific error
    console.warn("Password reset request with invalid email format.")
    return new Response(
      JSON.stringify({
        message:
          "If an account exists for the provided email, a password reset link has been sent.",
      }),
      { status: 200, headers: { "Content-Type": "application/json" } }
    )
  }

  const genericSuccessResponse = new Response(
    JSON.stringify({
      message:
        "If an account exists for this email, a password reset link has been sent.",
    }),
    { status: 200, headers: { "Content-Type": "application/json" } }
  )

  try {
    // Step 3: User Lookup
    const user = await readEmail(context, email)

    if (user && user.user_uuid) {
      // Step 4: Token Generation (token_value is now generated by createToken)
      const token_type = 'password_reset';
      const token_expires_in_seconds = 1 * 60 * 60; // 1 hour

      // Step 5: Store Token using createToken
      const tokenResult = await createToken(context, user.user_uuid, token_type, null, token_expires_in_seconds);

      if (tokenResult.error || !tokenResult.token_value) {
        console.error("Failed to create password reset token:", tokenResult.message);
        // Still return generic success to avoid leaking info, but log the error.
        return genericSuccessResponse;
      }
      const token_value = tokenResult.token_value;

      // Step 6: Email Sending (Simulated)
      console.log(
        `Password reset link for ${email}: /api/password/reset/set?token=${token_value} (Note: This is an API endpoint, a real link would go to a UI page).`
      )
    } else {
      // Email not found or user_uuid missing, log this internally
      console.log(
        `Password reset requested for non-existent or unlinked email: ${email}`
      )
    }

    // Step 7: Response (Always generic)
    return genericSuccessResponse
  } catch (error) {
    console.error("Error during password reset request:", error)
    return genericSuccessResponse
  }
}

export async function onRequest(context) {
  if (context.request.method === "POST") {
    return await onRequestPost(context) // Ensure onRequestPost is awaited
  }
  return new Response(JSON.stringify({ error: "Method Not Allowed" }), {
    status: 405,
    headers: { "Allow": "POST", "Content-Type": "application/json" },
  })
}
