// Outbound OAuth client — Puff as the *client* to GitHub / Google /
// Microsoft. Three steps:
//
//   1. buildAuthorizeUrl  — construct the URL Puff redirects the user to.
//   2. exchangeCode       — POST `code` to the provider's token endpoint and
//                           receive an access token.
//   3. fetchUserIdentity  — call the userinfo endpoint (and for GitHub, the
//                           /user/emails companion) and normalise the
//                           response.
//
// Provider-specific URLs and extractor functions live in src/oauth-providers.ts;
// this module is the protocol-level plumbing on top of them.

import type { NormalisedIdentity, ProviderConfig } from "./oauth-providers.js"

/**
 * Build the URL Puff should redirect the user to. Uses the Authorization
 * Code flow with S256 PKCE — both `state` and `code_challenge` MUST be
 * generated by the caller (see `oauth-state-cookie.ts`).
 */
export function buildAuthorizeUrl(opts: {
  provider: ProviderConfig
  client_id: string
  redirect_uri: string
  state: string
  code_challenge: string
}): string {
  const url = new URL(opts.provider.authorize_url)
  url.searchParams.set("response_type", "code")
  url.searchParams.set("client_id", opts.client_id)
  url.searchParams.set("redirect_uri", opts.redirect_uri)
  url.searchParams.set("scope", opts.provider.scopes.join(" "))
  url.searchParams.set("state", opts.state)
  url.searchParams.set("code_challenge", opts.code_challenge)
  url.searchParams.set("code_challenge_method", "S256")
  // Google + Microsoft honour these; GitHub ignores them.
  url.searchParams.set("access_type", "offline")
  return url.toString()
}

/**
 * POSTs the authorization code to the provider's token endpoint. Returns
 * the access token on success. PKCE verifier is mandatory — Puff always
 * uses PKCE on outbound flows.
 *
 * Providers vary on response shape and content type. GitHub returns
 * form-encoded by default; we send `Accept: application/json` to force a
 * JSON response across the board.
 */
export async function exchangeCode(opts: {
  provider: ProviderConfig
  client_id: string
  client_secret: string
  code: string
  redirect_uri: string
  code_verifier: string
}): Promise<Envelope<{ access_token: string; id_token: string | null }>> {
  const body = new URLSearchParams({
    grant_type: "authorization_code",
    client_id: opts.client_id,
    client_secret: opts.client_secret,
    code: opts.code,
    redirect_uri: opts.redirect_uri,
    code_verifier: opts.code_verifier,
  })
  try {
    const response = await fetch(opts.provider.token_url, {
      method: "POST",
      headers: {
        "Accept": "application/json",
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: body.toString(),
      signal: AbortSignal.timeout(10_000),
    })
    if (!response.ok) {
      const text = await response.text()
      console.error(
        `oauth-outbound exchangeCode (${opts.provider.name}): ${response.status} ${text.slice(0, 200)}`
      )
      return {
        success: false,
        message: "Could not exchange the authorization code.",
        status: 502,
      }
    }
    const parsed = (await response.json()) as {
      access_token?: unknown
      id_token?: unknown
    }
    if (typeof parsed.access_token !== "string" || parsed.access_token === "") {
      return {
        success: false,
        message: "Provider did not return an access token.",
        status: 502,
      }
    }
    return {
      success: true,
      access_token: parsed.access_token,
      id_token:
        typeof parsed.id_token === "string" && parsed.id_token !== ""
          ? parsed.id_token
          : null,
      status: 200,
    }
  } catch (error) {
    console.error("oauth-outbound exchangeCode network error:", error)
    return {
      error: true,
      message: "Network error while exchanging the authorization code.",
      details: error instanceof Error ? error.message : String(error),
      status: 502,
    }
  }
}

/**
 * Calls the provider's userinfo endpoint (and emails endpoint for GitHub)
 * with the access token and returns the normalised identity. The
 * provider's `normaliseUserinfo` does the per-provider field mapping.
 */
export async function fetchUserIdentity(
  provider: ProviderConfig,
  access_token: string,
  id_token: string | null = null
): Promise<Envelope<{ identity: NormalisedIdentity }>> {
  try {
    const headers: Record<string, string> = {
      "Authorization": `Bearer ${access_token}`,
      "Accept": "application/json",
      // GitHub's API requires a User-Agent. Harmless on the others.
      "User-Agent": "Puff/1.0",
    }
    const userinfoRes = await fetch(provider.userinfo_url, {
      headers,
      signal: AbortSignal.timeout(10_000),
    })
    if (!userinfoRes.ok) {
      console.error(
        `oauth-outbound fetchUserIdentity (${provider.name}): userinfo ${userinfoRes.status}`
      )
      return {
        success: false,
        message: "Could not read your profile from the provider.",
        status: 502,
      }
    }
    const userinfo = (await userinfoRes.json()) as unknown

    let emails: unknown = undefined
    if (provider.emails_url) {
      try {
        const emailsRes = await fetch(provider.emails_url, {
          headers,
          signal: AbortSignal.timeout(10_000),
        })
        if (emailsRes.ok) {
          emails = await emailsRes.json()
        }
      } catch (error) {
        // The userinfo response is enough to identify the user; the emails
        // endpoint is supplementary. Logging without aborting matches the
        // resend-on-failure pattern elsewhere.
        console.error(
          `oauth-outbound fetchUserIdentity (${provider.name}): emails fetch failed:`,
          error
        )
      }
    }

    const identity = provider.normaliseUserinfo(
      userinfo,
      emails,
      id_token ?? undefined
    )
    if (!identity) {
      return {
        success: false,
        message: "Provider returned an unrecognisable profile.",
        status: 502,
      }
    }
    return { success: true, identity, status: 200 }
  } catch (error) {
    console.error("oauth-outbound fetchUserIdentity network error:", error)
    return {
      error: true,
      message: "Network error reading your profile from the provider.",
      details: error instanceof Error ? error.message : String(error),
      status: 502,
    }
  }
}
