CREATE TABLE public.oauth_grants (
    grant_value STRING NOT NULL,
    grant_type STRING NOT NULL,
    user_uuid STRING NOT NULL,
    app_uuid STRING NOT NULL,
    org_uuid STRING NULL,
    scopes STRING[] NOT NULL,
    redirect_uri STRING NULL,
    code_challenge STRING NULL,
    code_challenge_method STRING NULL,
    nonce STRING NULL,
    parent_grant_value STRING NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP():::TIMESTAMP,
    is_used BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT oauth_grants_pkey PRIMARY KEY (grant_value ASC),
    CONSTRAINT oauth_grants_user_uuid_fkey FOREIGN KEY (user_uuid) REFERENCES public.users(user_uuid) ON DELETE CASCADE,
    CONSTRAINT oauth_grants_app_uuid_fkey FOREIGN KEY (app_uuid) REFERENCES public.apps(app_uuid) ON DELETE CASCADE,
    CONSTRAINT oauth_grants_org_uuid_fkey FOREIGN KEY (org_uuid) REFERENCES public.organisations(org_uuid) ON DELETE SET NULL,
    INDEX idx_oauth_grants_user_uuid_app_uuid (user_uuid, app_uuid ASC),
    INDEX idx_oauth_grants_app_uuid (app_uuid ASC),
    INDEX idx_oauth_grants_expires_at (expires_at ASC),
    INDEX idx_oauth_grants_parent_grant_value (parent_grant_value ASC)
) LOCALITY REGIONAL BY TABLE IN PRIMARY REGION
