name: "CI: Build"

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - cf-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: "latest"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
